[project]
name = "robot-questionnaire"
version = "0.1.0"
description = "Robot questionnaire interactif avec openAI"
authors = [
    {name = "Yazid",email = "alouiyaz78@gmail.com"}
]
license = {text = "Yazid"}
readme = "README.md"
requires-python = ">3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
